### ISSUE TITLE
Fiery Knife is not emissive and has holes in its handle

### ISSUE THREAD

**Issue by saltyseadoggo** [brnbrd/Delightful#40]
**Describe the bug**:
The Fiery Knife is not emissive like the other fiery gear items in Twilight Forest. There is also a transparent pixel in its handle, and a pixel that goes from transparent to opaque repeatedly.

**To Reproduce**:
- Place TF fiery pickaxe in item frame
- Place Delightful fiery knife in item frame

**Expected behavior**:
The knife would be emissive like the pickaxe, and would not have transparent pixels in its handle.

**Screenshots**:
![2023-05-10_13 05 22](https://github.com/brnbrd/Delightful/assets/69029346/8788f4d9-147a-4c72-be7e-22e8e72ea010)

**Versions**:
Forge 43.2.8
Twilight Forest 4.2.1518
Farmer's Delight 1.2.0
Delightful 3.2.4

**Comment by brnbrd** [comment]
The texture has already been updated so that fix is coming shortly. I'm looking into the emissiveness.
I see how they achieve it: https://github.com/TeamTwilight/twilightforest/blob/1.19.2/src/generated/resources/assets/twilightforest/models/item/fiery_sword.json
Should be pretty simple to sort out.

**Comment by brnbrd** [comment]
Fixed in v3.3
