### ISSUE TITLE
[Suggestion] Make Enderite knives made from different mods have different color and texture

### ISSUE THREAD

**Issue by chemlzh** [brnbrd/Delightful#66]
I have searched mods on CurseForge using "Enderite", and it gaves two kinds of Enderite. The first kind has a purple-to-magenta color, which includes [LieOnLion's Enderite](https://www.curseforge.com/minecraft/mc-mods/enderite-lieonlion) and [Enderite&Overite](https://www.curseforge.com/minecraft/mc-mods/enderite-overite). And the second kind has a dark-green-to-cyan color, which includes [Enderite Mod for Forge](https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-forge) and [Enderite Mod CJ version](https://www.curseforge.com/minecraft/mc-mods/enderite-cj-edition). However, the latest version of Delightful only has the kind of Enderite knives, which doesn't fit well with the second kind of Enderite mods.

I think it's better to separate Enderite knives made from LieOnLion's Enderite from Enderite made from pitti's Enderite. As suggested by Colonel_Gerdauf on CurseForge comment pages in #6069649:

> I am hoping for a way for the mod to make Enderite from LieOnLite and the like from pitti11 cosmetically different.
> The reason I prefer the pitti11 models is because the teal-like colours make more sense to me. Not to mention, in my opinion, the enderite from LieOnLite is too close to amethyst.

Therefore I suggest that Enderite knives should have two kinds of textures. The first is the original light magenta texture whose color resembles LieOnLion's Enderite. The second has a dark-cyan texture which resembles pitti's Enderite.

I hope this suggestion may be accepted. Thank you!

**Comment by championhestu** [comment]
I'm the artist for the mod, and have already shut this down once before. This is absolutely something you can fix yourself using a resource pack, because one way or the other, people are going to use different mods that use different colors for a material of the same name. Coding a ton of different knives into the mod just to separate two out of however many Enderite mods is not only bloat, it sets a precedent for every other material used within it.

In response to Colonel_Gerdauf's request, I made an Enderite Knife texture using pitti11's Enderite colorscheme a while back, so they could make their own resource pack. You can find that sprite [[HERE]](https://cdn.discordapp.com/attachments/1072598112629174376/1133873566102855860/enderite_knife.png?ex=659f0c0c&is=658c970c&hm=bbae24336bab3bda20f93e4e61b4fd3240ebcee5470800836577f073ea060084&).
